title: "Кривая"
description: "Ювелирный бренд, где в кривых линиях — жизнь."
locale: "ru-RU"
theme: minimal-mistakes-jekyll

# Базовые настройки
url: "https://kust12.github.io"
baseurl: "/minimal-mistakes"
repository: "kust12/minimal-mistakes"

# Включаем поддержку нужных страниц
paginate: 5
paginate_path: /page:num/

# Отключаем блог
collections:
  portfolio:
    output: true
    permalink: /каталог/:name/

# Меню
nav:
  - title: "Главная"
    url: /
  - title: "Каталог"
    url: /каталог/
  - title: "О бренде"
    url: /о-бренде/
  - title: "Контакты"
    url: /контакты/

# SEO и соцсети
author:
  name: "Кривая"
  avatar: "/assets/images/logo.png" # логотип, если будет
  bio: "Минималистичные украшения, в которых чувствуется жизнь."

# Удаляем лишнее
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      show_date: false
      share: false
      related: false
      comments: false

# Локализация
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
